// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.IPrefer
{
	[IAlias("Performance_Threshold")]
    public partial interface IPerformance_Threshold :ZZHMHN.IBase.I_Entity.IEntity
    {
        [Required]
		[PrimaryKey]
        short SurfaceTypeCODE { get; set;}		
        [Required]
		[PrimaryKey]
        short FunClassCODE { get; set;}		
        double? VolCapRatio { get; set;}
        double? NumAccidents { get; set;}
        double? Roughness { get; set;}
        double? PCI_Preventive { get; set;}
        double? PCI_Corrective { get; set;}
        double? PCI_Rehabilitation { get; set;}
        double? PCI_Reconstruction { get; set;}
        double? WCI_Minor { get; set;}
        double? WCI_Remove_Replace { get; set;}
        double? WCI_Bridge { get; set;}
        double? FN { get; set;}
    }
}
#pragma warning restore 1591
