// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.IPrefer
{
	[IAlias("Priority_Factors")]
    public partial interface IPriority_Factor :ZZHMHN.IBase.I_Entity.IEntity
    {
        [Required]
		[PrimaryKey]
        short CODE { get; set;}		
        short? LAADT_LScore { get; set;}
        short? LAADT_MScore { get; set;}
        short? LAADT_HScore { get; set;}
        short? MAADT_LScore { get; set;}
        short? MAADT_MScore { get; set;}
        short? MAADT_HScore { get; set;}
        short? HAADT_LScore { get; set;}
        short? HAADT_MScore { get; set;}
        short? HAADT_HScore { get; set;}
    }
}
#pragma warning restore 1591
