// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.IPrefer
{
	[IAlias("Unit_Cost")]
    public partial interface IUnit_Cost :ZZHMHN.IBase.I_Entity.IEntity
    {
        [Required]
		[PrimaryKey]
        short CODE { get; set;}		
        decimal? Service_Imp_Cost { get; set;}
        decimal? Safety_Imp { get; set;}
        decimal? Preventive_Maint { get; set;}
        decimal? Corrective_Maint { get; set;}
        decimal? Min_BridgeSurfRepair { get; set;}
        decimal? BridgeWearCourseRepair { get; set;}
        decimal? BridgeDeckReplace { get; set;}
    }
}
#pragma warning restore 1591
