// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.IPCIWCI
{
	[Alias("COEFF_C")]
    public partial class COEFF_C :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.IPCIWCI.ICOEFF_C
    {
		public COEFF_C()
		{
		}

        [Alias("Structure Type")]
        [Required]
		[PrimaryKey]
        public short Structure_Type { get; set;}		
        [Required]
		[PrimaryKey]
        public int Quantity { get; set;}		
        [Alias("Max DV")]
        public int? Max_DV { get; set;}
        public double? C0 { get; set;}
        public double? C1 { get; set;}
        public double? C2 { get; set;}
        public double? C3 { get; set;}
        public double? C4 { get; set;}
        public double? C5 { get; set;}
        public double? C6 { get; set;}
    }
}
#pragma warning restore 1591
