// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Ihpms
{
	[Alias("HISTPERF")]
    public partial class HISTPERF :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.Ihpms.IHISTPERF
    {
		public HISTPERF()
		{
		}

        [Required]
		[PrimaryKey]
        public int SEGID { get; set;}		
        [Required]
		[PrimaryKey]
        public int RECORDNUM { get; set;}		
        public int? PERFYEAR { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string FUNCLASS { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        public string NUMLANES { get; set;}
        public double? CONSTYEAR { get; set;}
        public int? IRIMEAN { get; set;}
        public int? RGHMEAN { get; set;}
        public DateTime? RGHDATE { get; set;}
        public DateTime? PCIDATE { get; set;}
        public int? PCIMEAN { get; set;}
        public DateTime? FRCDATE { get; set;}
        public short? FRCMEAN { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string PVMTTYPE { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string SURFTYPE { get; set;}
        public float? SCEFF { get; set;}
        public int? SCEFFYEAR { get; set;}
        public int? AADT { get; set;}
        public int? CURADTYEAR { get; set;}
        public float? TRKPCTAADT { get; set;}
        public float? TRKWTPAT { get; set;}
        public DateTime? ARCHDATE { get; set;}
    }
}
#pragma warning restore 1591
