// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Ihpms
{
	[Alias("INVNTORY")]
    public partial class INVNTORY :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.Ihpms.IINVNTORY
    {
		public INVNTORY()
		{
		}

        public int? RDWAYID { get; set;}
        [Required]
		[PrimaryKey]
        public int SEGID { get; set;}		
        public int? MAPOBJECTID { get; set;}
        public float? BEGINMP { get; set;}
        public float? ENDMP { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        public string MAINTDIST { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        public string ALDDIST { get; set;}
		/// <summary>
        /// length: 40
        /// </summary>
        [StringLength(40)]
        public string FROMLOC { get; set;}
		/// <summary>
        /// length: 40
        /// </summary>
        [StringLength(40)]
        public string TOLOC { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        public string DIRECTION { get; set;}
		/// <summary>
        /// length: 25
        /// </summary>
        [StringLength(25)]
        public string FUNCLASS { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        public string SECTTYPE { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        public string NUMLANES { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        public string NUMLANESP { get; set;}
        public int? SURFWIDTH { get; set;}
		/// <summary>
        /// length: 3
        /// </summary>
        [StringLength(3)]
        public string INTERSECT { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        public string MEDIAN { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string RSHLDRTYPE { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        public string RCURBTYPE { get; set;}
        public short? RCURBEXP { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string RCURBCOND { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string LSHLDRTYPE { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        public string LCURBTYPE { get; set;}
        public short? LCURBEXP { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string LCURBCOND { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string SWTYPE { get; set;}
        public float? SWWIDTH { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string SWCOND { get; set;}
        public short? SWRAMPS { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        public string QUADRANT { get; set;}
		/// <summary>
        /// length: 6
        /// </summary>
        [StringLength(6)]
        public string FROMNODE { get; set;}
		/// <summary>
        /// length: 6
        /// </summary>
        [StringLength(6)]
        public string TONODE { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        public string CONTRACTN { get; set;}
        public DateTime? CONTRACTD { get; set;}
		/// <summary>
        /// length: 60
        /// </summary>
        [StringLength(60)]
        public string COMMENTS { get; set;}
        public DateTime? REVDATE { get; set;}
    }
}
#pragma warning restore 1591
