// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Ihpms
{
	[Alias("RDFRC")]
    public partial class RDFRC :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.Ihpms.IRDFRC
    {
		public RDFRC()
		{
		}

        [Required]
		[PrimaryKey]
        public int SEGID { get; set;}		
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        public string DEVICE { get; set;}
        public DateTime? FRCDATE { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        public string FRCLANE { get; set;}
        public double? FRCMAX { get; set;}
        public short? FRCMEAN { get; set;}
        public double? FRCMIN { get; set;}
        public double? FRCSTDDEV { get; set;}
        public double? NPTS { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        public string COMMENTS { get; set;}
    }
}
#pragma warning restore 1591
