// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Ihpms
{
	[Alias("RDLAY")]
    public partial class RDLAY :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.Ihpms.IRDLAY
    {
		public RDLAY()
		{
		}

        [Required]
		[PrimaryKey]
        public int SEGID { get; set;}		
        [Required]
		[PrimaryKey]
        public float LAYERNUM { get; set;}		
        public short? LAYERCODE { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        public string LAYERTYPE { get; set;}
        public float? LAYERTHICK { get; set;}
        public float? LAYERM { get; set;}
		/// <summary>
        /// length: 10
        /// </summary>
        [StringLength(10)]
        public string MTRLTYPE { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        public string ASPHTYPE { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        public string STRGTHTYPE { get; set;}
        public float? STRGTHVAL { get; set;}
        public short? STRGTHYEAR { get; set;}
        public short? CONSTYEAR { get; set;}
		/// <summary>
        /// length: 60
        /// </summary>
        [StringLength(60)]
        public string COMMENTS { get; set;}
        public DateTime? REVDATE { get; set;}
		/// <summary>
        /// length: 10
        /// </summary>
        [StringLength(10)]
        public string FILENUM { get; set;}
    }
}
#pragma warning restore 1591
