// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Ihpms
{
	[Alias("RDPCI")]
    public partial class RDPCI :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.Ihpms.IRDPCI
    {
		public RDPCI()
		{
		}

        [Required]
		[PrimaryKey]
        public int SEGID { get; set;}		
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        public string DEVICE { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string SURVTYPE { get; set;}
        public DateTime? PCIDATE { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        public string PCILANE { get; set;}
        public short? PCIMAX { get; set;}
        public short? PCIMEAN { get; set;}
        public short? PCIMIN { get; set;}
        public float? PCISTDDEV { get; set;}
        public int? NUMSAMP { get; set;}
        public float? FATCRK_AC { get; set;}
        public float? BLEED_AC { get; set;}
        public float? BLOCK_AC { get; set;}
        public float? BUMPS_AC { get; set;}
        public float? CORR_AC { get; set;}
        public float? DEPRES_AC { get; set;}
        public float? EDGECRK_AC { get; set;}
        public float? JTREFC_AC { get; set;}
        public float? LSDROP_AC { get; set;}
        public float? LTCRK_AC { get; set;}
        public float? PATCH_AC { get; set;}
        public float? POLISH_AC { get; set;}
        public float? PHOLES_AC { get; set;}
        public float? RRX_AC { get; set;}
        public float? RUT_AC { get; set;}
        public float? SHOVE_AC { get; set;}
        public float? SLPCRK_AC { get; set;}
        public float? SWELL_AC { get; set;}
        public float? RAVEL_AC { get; set;}
        public float? BLOWUP_PC { get; set;}
        public float? CBRK_PC { get; set;}
        public float? DSLAB_PC { get; set;}
        public float? DCRK_PC { get; set;}
        public float? FAULT_PC { get; set;}
        public float? JSDAM_PC { get; set;}
        public float? LSDROP_PC { get; set;}
        public float? LINCRK_PC { get; set;}
        public float? LPATCH_PC { get; set;}
        public float? SPATCH_PC { get; set;}
        public float? POLISH_PC { get; set;}
        public float? POPOUT_PC { get; set;}
        public float? PUMP_PC { get; set;}
        public float? POUT_PC { get; set;}
        public float? RRX_PC { get; set;}
        public float? MAPCRK_PC { get; set;}
        public float? SHRCRK_PC { get; set;}
        public float? CSPALL_PC { get; set;}
        public float? JSPALL_PC { get; set;}
    }
}
#pragma warning restore 1591
