// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Ihpms
{
	[Alias("RDSTC")]
    public partial class RDSTC :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.Ihpms.IRDSTC
    {
		public RDSTC()
		{
		}

        [Required]
		[PrimaryKey]
        public int SEGID { get; set;}		
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        public string PVMTTYPE { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        public string SURFTYPE { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string LANECODE { get; set;}
        public short? LAYERCODE { get; set;}
        public float? COEFFDRAIN { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string DOWEL { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        public string DRAINTYPE { get; set;}
        public short? JOINTSPACE { get; set;}
        public float? J { get; set;}
        public short? KCOMP { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        public string LOSSUPPORT { get; set;}
        public float? SCEFF { get; set;}
        public short? SCEFFYEAR { get; set;}
        public float? SCO { get; set;}
        public short? SUBCBR { get; set;}
		/// <summary>
        /// length: 120
        /// </summary>
        [StringLength(120)]
        public string COMMENTS { get; set;}
        public DateTime? REVDATE { get; set;}
    }
}
#pragma warning restore 1591
