// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.IPCIWCI
{
	[Alias("COEFF_A")]
    public partial class COEFF_A :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.IPCIWCI.ICOEFF_A
    {
		public COEFF_A()
		{
		}

        [Alias("Distress ID")]
        [Required]
		[PrimaryKey]
        public short Distress_ID { get; set;}		
        [Required]
		[PrimaryKey]
        public short Severity { get; set;}		
        [Alias("Max Distress Density")]
        [Required]
		[PrimaryKey]
        public float Max_Distress_Density { get; set;}		
        public double? A0 { get; set;}
        public double? A1 { get; set;}
        public double? A2 { get; set;}
        public double? A3 { get; set;}
        public double? A4 { get; set;}
        public double? A5 { get; set;}
        public double? A6 { get; set;}
    }
}
#pragma warning restore 1591
