// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.IArchive
{
	[IAlias("RDDIST")]
    public partial interface IRDDIST :ZZHMHN.IBase.I_Entity.IEntity
    {
        [Required]
		[PrimaryKey]
        int ArchID { get; set;}		
        double? SEGID { get; set;}
        double? DISTID { get; set;}
        DateTime? DISTDATE { get; set;}
        double? QUANLOW { get; set;}
        double? QUANMED { get; set;}
        double? QUANHI { get; set;}
        double? QUANNA { get; set;}
        double? TOTSIZE { get; set;}
    }
}
#pragma warning restore 1591
