// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.IArchive
{
	[IAlias("SAMPHEADER")]
    public partial interface ISAMPHEADER :ZZHMHN.IBase.I_Entity.IEntity
    {
        [Required]
		[PrimaryKey]
        int ArchID { get; set;}		
		/// <summary>
        /// length: 30
        /// </summary>
        [StringLength(30)]
        string SAMPID { get; set;}
        int? SEGID { get; set;}
        DateTime? SURVDATE { get; set;}
        double? SURVLANE { get; set;}
        double? SBEGINPT { get; set;}
        double? SENDPT { get; set;}
        double? SAMPSIZE { get; set;}
		/// <summary>
        /// length: 20
        /// </summary>
        [StringLength(20)]
        string SURVINIT { get; set;}
		/// <summary>
        /// length: 120
        /// </summary>
        [StringLength(120)]
        string COMMENTS { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string SAMPUNITTYPE { get; set;}
        double? SAMPPCI { get; set;}
        double? SAMPPCIDEVICE { get; set;}
    }
}
#pragma warning restore 1591
