// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.IPCIWCI
{
	[IAlias("COEFF_C")]
    public partial interface ICOEFF_C :ZZHMHN.IBase.I_Entity.IEntity
    {
        [Alias("Structure Type")]
        [Required]
		[PrimaryKey]
        short Structure_Type { get; set;}		
        [Required]
		[PrimaryKey]
        int Quantity { get; set;}		
        [Alias("Max DV")]
        int? Max_DV { get; set;}
        double? C0 { get; set;}
        double? C1 { get; set;}
        double? C2 { get; set;}
        double? C3 { get; set;}
        double? C4 { get; set;}
        double? C5 { get; set;}
        double? C6 { get; set;}
    }
}
#pragma warning restore 1591
