// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.IPCIWCI
{
	[IAlias("COEFF_A")]
    public partial interface ICOEFF_A :ZZHMHN.IBase.I_Entity.IEntity
    {
        [Alias("Distress ID")]
        [Required]
		[PrimaryKey]
        short Distress_ID { get; set;}		
        [Required]
		[PrimaryKey]
        short Severity { get; set;}		
        [Alias("Max Distress Density")]
        [Required]
		[PrimaryKey]
        float Max_Distress_Density { get; set;}		
        double? A0 { get; set;}
        double? A1 { get; set;}
        double? A2 { get; set;}
        double? A3 { get; set;}
        double? A4 { get; set;}
        double? A5 { get; set;}
        double? A6 { get; set;}
    }
}
#pragma warning restore 1591
