// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.Ihpms
{
	[IAlias("ACTIVITY")]
    public partial interface IACTIVITY :ZZHMHN.IBase.I_Entity.IEntity
    {
        [Alias("ACTIVITY")]
        [AutoIncrement]
		[PrimaryKey]
        decimal _ACTIVITY { get; set;}		
        int? SET_ID { get; set;}
        decimal? COST { get; set;}
		/// <summary>
        /// length: 255
        /// </summary>
        [StringLength(255)]
        string DESCRIPT { get; set;}
        float? ADJFACTOR { get; set;}
    }
}
#pragma warning restore 1591
