// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.Ihpms
{
	[IAlias("CODEINFO")]
    public partial interface ICODEINFO :ZZHMHN.IBase.I_Entity.IEntity
    {
		/// <summary>
        /// length: 19
        /// </summary>
        [StringLength(19)]
        [Required]
		[PrimaryKey]
        string STNDNAME { get; set;}		
        [Required]
		[PrimaryKey]
        int CODE { get; set;}		
		/// <summary>
        /// length: 60
        /// </summary>
        [StringLength(60)]
        string INFO { get; set;}
		/// <summary>
        /// length: 30
        /// </summary>
        [StringLength(30)]
        string LIMITINFO { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string CHECKED { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string CATCHK { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string MENUCHECK { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string ACTIVE { get; set;}
		/// <summary>
        /// length: 19
        /// </summary>
        [StringLength(19)]
        string STDNAME { get; set;}
		/// <summary>
        /// length: 25
        /// </summary>
        [StringLength(25)]
        string CATTITLE { get; set;}
    }
}
#pragma warning restore 1591
