// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.Ihpms
{
	[IAlias("DISTTYPE")]
    public partial interface IDISTTYPE :ZZHMHN.IBase.I_Entity.IEntity
    {
        [Alias("DISTRESS ID")]
        [Required]
		[PrimaryKey]
        double DISTRESS_ID { get; set;}		
        [Alias("DISTRESS NAME")]
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        string DISTRESS_NAME { get; set;}
        [Alias("DISTRESS UNIT")]
        double? DISTRESS_UNIT { get; set;}
        double? Severity { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        string STRUCTURETYPE { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        string RDPCINAME { get; set;}
    }
}
#pragma warning restore 1591
