// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.Ihpms
{
	[IAlias("DTBRANCH")]
    public partial interface IDTBRANCH :ZZHMHN.IBase.I_Entity.IEntity
    {
        [Required]
		[PrimaryKey]
        int SET_ID { get; set;}		
        [Required]
		[PrimaryKey]
        int PARAM_ID { get; set;}		
        [Required]
		[PrimaryKey]
        short RANK { get; set;}		
        float? TRIGGER { get; set;}
        short? INCLUSIVE { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        string RESULT { get; set;}
		/// <summary>
        /// length: 10
        /// </summary>
        [StringLength(10)]
        string Column_7 { get; set;}
    }
}
#pragma warning restore 1591
