// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.Ihpms
{
	[IAlias("DTPARAM")]
    public partial interface IDTPARAM :ZZHMHN.IBase.I_Entity.IEntity
    {
        [AutoIncrement]
		[PrimaryKey]
        decimal PARAM_ID { get; set;}		
        [Required]
		[PrimaryKey]
        int SET_ID { get; set;}		
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        string PARAM_NAME { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        string STNDNAME { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string TYPE_DCSN { get; set;}
        short? DEFAULT_BR { get; set;}
        int? PARAM_ORD { get; set;}
        short? P1 { get; set;}
        short? P2 { get; set;}
        short? P3 { get; set;}
    }
}
#pragma warning restore 1591
