// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.Ihpms
{
	[IAlias("HISTPERF")]
    public partial interface IHISTPERF :ZZHMHN.IBase.I_Entity.IEntity
    {
        [Required]
		[PrimaryKey]
        int SEGID { get; set;}		
        [Required]
		[PrimaryKey]
        int RECORDNUM { get; set;}		
        int? PERFYEAR { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string FUNCLASS { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        string NUMLANES { get; set;}
        double? CONSTYEAR { get; set;}
        int? IRIMEAN { get; set;}
        int? RGHMEAN { get; set;}
        DateTime? RGHDATE { get; set;}
        DateTime? PCIDATE { get; set;}
        int? PCIMEAN { get; set;}
        DateTime? FRCDATE { get; set;}
        short? FRCMEAN { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string PVMTTYPE { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string SURFTYPE { get; set;}
        float? SCEFF { get; set;}
        int? SCEFFYEAR { get; set;}
        int? AADT { get; set;}
        int? CURADTYEAR { get; set;}
        float? TRKPCTAADT { get; set;}
        float? TRKWTPAT { get; set;}
        DateTime? ARCHDATE { get; set;}
    }
}
#pragma warning restore 1591
