// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.Ihpms
{
	[IAlias("INVNTORY")]
    public partial interface IINVNTORY :ZZHMHN.IBase.I_Entity.IEntity
    {
        int? RDWAYID { get; set;}
        [Required]
		[PrimaryKey]
        int SEGID { get; set;}		
        int? MAPOBJECTID { get; set;}
        float? BEGINMP { get; set;}
        float? ENDMP { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        string MAINTDIST { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        string ALDDIST { get; set;}
		/// <summary>
        /// length: 40
        /// </summary>
        [StringLength(40)]
        string FROMLOC { get; set;}
		/// <summary>
        /// length: 40
        /// </summary>
        [StringLength(40)]
        string TOLOC { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        string DIRECTION { get; set;}
		/// <summary>
        /// length: 25
        /// </summary>
        [StringLength(25)]
        string FUNCLASS { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string SECTTYPE { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        string NUMLANES { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        string NUMLANESP { get; set;}
        int? SURFWIDTH { get; set;}
		/// <summary>
        /// length: 3
        /// </summary>
        [StringLength(3)]
        string INTERSECT { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        string MEDIAN { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string RSHLDRTYPE { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        string RCURBTYPE { get; set;}
        short? RCURBEXP { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string RCURBCOND { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string LSHLDRTYPE { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        string LCURBTYPE { get; set;}
        short? LCURBEXP { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string LCURBCOND { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string SWTYPE { get; set;}
        float? SWWIDTH { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string SWCOND { get; set;}
        short? SWRAMPS { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        string QUADRANT { get; set;}
		/// <summary>
        /// length: 6
        /// </summary>
        [StringLength(6)]
        string FROMNODE { get; set;}
		/// <summary>
        /// length: 6
        /// </summary>
        [StringLength(6)]
        string TONODE { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string CONTRACTN { get; set;}
        DateTime? CONTRACTD { get; set;}
		/// <summary>
        /// length: 60
        /// </summary>
        [StringLength(60)]
        string COMMENTS { get; set;}
        DateTime? REVDATE { get; set;}
    }
}
#pragma warning restore 1591
