// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.Ihpms
{
	[IAlias("PMSELTS")]
    public partial interface IPMSELT :ZZHMHN.IBase.I_Entity.IEntity
    {
		/// <summary>
        /// length: 25
        /// </summary>
        [StringLength(25)]
        [Required]
		[PrimaryKey]
        string STND_NAME { get; set;}		
        bool? TBL_AVG { get; set;}
        bool? TBL_MAX { get; set;}
        bool? TBL_SUM { get; set;}
        bool? TBL_MIN { get; set;}
		/// <summary>
        /// length: 20
        /// </summary>
        [StringLength(20)]
        string ENGL_NAME { get; set;}
		/// <summary>
        /// length: 60
        /// </summary>
        [StringLength(60)]
        string DEFINITION { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string TYPE { get; set;}
        short? EDITORDER { get; set;}
		/// <summary>
        /// length: 7
        /// </summary>
        [StringLength(7)]
        string UNITS { get; set;}
        int? FLD_POS { get; set;}
        int? FLD_WIDTH { get; set;}
        float? FLD_DEC { get; set;}
        short? UPDATE_MULT { get; set;}
		/// <summary>
        /// length: 8
        /// </summary>
        [StringLength(8)]
        string SELCT_NDX { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string STND_SELCT { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string CSTM_SELCT { get; set;}
        short? DCSN_TREE { get; set;}
        double? SUM_TBL { get; set;}
		/// <summary>
        /// length: 21
        /// </summary>
        [StringLength(21)]
        string TBL_FMT { get; set;}
		/// <summary>
        /// length: 20
        /// </summary>
        [StringLength(20)]
        string SUM_HDG1 { get; set;}
		/// <summary>
        /// length: 20
        /// </summary>
        [StringLength(20)]
        string SUM_HDG2 { get; set;}
		/// <summary>
        /// length: 20
        /// </summary>
        [StringLength(20)]
        string SUM_HDG3 { get; set;}
        int? DETAIL_TBL { get; set;}
        int? DT_XPOS { get; set;}
        int? DT_YPOS { get; set;}
        int? CSTM_TBL { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string PIE { get; set;}
        [Required]
        bool CHART_CAT { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string CHART_VAL { get; set;}
        [Required]
        bool CHART_SER { get; set;}
        [Required]
        bool GRAPH_X { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string GRAPH_Y { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string SORT_OPTS { get; set;}
        short? MAPOPTIONS { get; set;}
        int? MAPPRIMARY { get; set;}
		/// <summary>
        /// length: 8
        /// </summary>
        [StringLength(8)]
        string MAPCOLOR { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string ATTR1_P { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string ATTR2_P { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string ATTR3_P { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string ATTR4_P { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string ATTR5_P { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string ATTR6_P { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string ATTR7_P { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string ATTR8_P { get; set;}
		/// <summary>
        /// length: 20
        /// </summary>
        [StringLength(20)]
        string LTITLE2_P { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string LEGEND1_P { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string LEGEND2_P { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string LEGEND3_P { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string LEGEND4_P { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string LEGEND5_P { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string LEGEND6_P { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string LEGEND7_P { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string LEGEND8_P { get; set;}
        double? MAPSECOND { get; set;}
		/// <summary>
        /// length: 4
        /// </summary>
        [StringLength(4)]
        string MAPTHICK { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string ATTR1_S { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string ATTR2_S { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string ATTR3_S { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string ATTR4_S { get; set;}
		/// <summary>
        /// length: 20
        /// </summary>
        [StringLength(20)]
        string LTITLE2_S { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string LEGEND1_S { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string LEGEND2_S { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string LEGEND3_S { get; set;}
		/// <summary>
        /// length: 15
        /// </summary>
        [StringLength(15)]
        string LEGEND4_S { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        string VAL_OP1 { get; set;}
		/// <summary>
        /// length: 19
        /// </summary>
        [StringLength(19)]
        string VAL_ARG1 { get; set;}
        int? INFOLENGTH { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string VAL_LOG_OP { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        string VAL_OP2 { get; set;}
		/// <summary>
        /// length: 19
        /// </summary>
        [StringLength(19)]
        string VAL_ARG2 { get; set;}
		/// <summary>
        /// length: 40
        /// </summary>
        [StringLength(40)]
        string COMMENTS { get; set;}
        DateTime? REVDATE { get; set;}
    }
}
#pragma warning restore 1591
