// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.Ihpms
{
	[IAlias("PREF_ITEMS")]
    public partial interface IPREF_ITEM :ZZHMHN.IBase.I_Entity.IEntity
    {
		/// <summary>
        /// length: 30
        /// </summary>
        [StringLength(30)]
        [Required]
		[PrimaryKey]
        string ITEM { get; set;}		
		/// <summary>
        /// length: 20
        /// </summary>
        [StringLength(20)]
        string VALUE { get; set;}
    }
}
#pragma warning restore 1591
