// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.Ihpms
{
	[IAlias("RDFRC")]
    public partial interface IRDFRC :ZZHMHN.IBase.I_Entity.IEntity
    {
        [Required]
		[PrimaryKey]
        int SEGID { get; set;}		
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        string DEVICE { get; set;}
        DateTime? FRCDATE { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        string FRCLANE { get; set;}
        double? FRCMAX { get; set;}
        short? FRCMEAN { get; set;}
        double? FRCMIN { get; set;}
        double? FRCSTDDEV { get; set;}
        double? NPTS { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        string COMMENTS { get; set;}
    }
}
#pragma warning restore 1591
