// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.Ihpms
{
	[IAlias("RDPCI")]
    public partial interface IRDPCI :ZZHMHN.IBase.I_Entity.IEntity
    {
        [Required]
		[PrimaryKey]
        int SEGID { get; set;}		
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        string DEVICE { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string SURVTYPE { get; set;}
        DateTime? PCIDATE { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        string PCILANE { get; set;}
        short? PCIMAX { get; set;}
        short? PCIMEAN { get; set;}
        short? PCIMIN { get; set;}
        float? PCISTDDEV { get; set;}
        int? NUMSAMP { get; set;}
        float? FATCRK_AC { get; set;}
        float? BLEED_AC { get; set;}
        float? BLOCK_AC { get; set;}
        float? BUMPS_AC { get; set;}
        float? CORR_AC { get; set;}
        float? DEPRES_AC { get; set;}
        float? EDGECRK_AC { get; set;}
        float? JTREFC_AC { get; set;}
        float? LSDROP_AC { get; set;}
        float? LTCRK_AC { get; set;}
        float? PATCH_AC { get; set;}
        float? POLISH_AC { get; set;}
        float? PHOLES_AC { get; set;}
        float? RRX_AC { get; set;}
        float? RUT_AC { get; set;}
        float? SHOVE_AC { get; set;}
        float? SLPCRK_AC { get; set;}
        float? SWELL_AC { get; set;}
        float? RAVEL_AC { get; set;}
        float? BLOWUP_PC { get; set;}
        float? CBRK_PC { get; set;}
        float? DSLAB_PC { get; set;}
        float? DCRK_PC { get; set;}
        float? FAULT_PC { get; set;}
        float? JSDAM_PC { get; set;}
        float? LSDROP_PC { get; set;}
        float? LINCRK_PC { get; set;}
        float? LPATCH_PC { get; set;}
        float? SPATCH_PC { get; set;}
        float? POLISH_PC { get; set;}
        float? POPOUT_PC { get; set;}
        float? PUMP_PC { get; set;}
        float? POUT_PC { get; set;}
        float? RRX_PC { get; set;}
        float? MAPCRK_PC { get; set;}
        float? SHRCRK_PC { get; set;}
        float? CSPALL_PC { get; set;}
        float? JSPALL_PC { get; set;}
    }
}
#pragma warning restore 1591
