// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.Ihpms
{
	[IAlias("RDSTC")]
    public partial interface IRDSTC :ZZHMHN.IBase.I_Entity.IEntity
    {
        [Required]
		[PrimaryKey]
        int SEGID { get; set;}		
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        string PVMTTYPE { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        string SURFTYPE { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string LANECODE { get; set;}
        short? LAYERCODE { get; set;}
        float? COEFFDRAIN { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string DOWEL { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        string DRAINTYPE { get; set;}
        short? JOINTSPACE { get; set;}
        float? J { get; set;}
        short? KCOMP { get; set;}
		/// <summary>
        /// length: 2
        /// </summary>
        [StringLength(2)]
        string LOSSUPPORT { get; set;}
        float? SCEFF { get; set;}
        short? SCEFFYEAR { get; set;}
        float? SCO { get; set;}
        short? SUBCBR { get; set;}
		/// <summary>
        /// length: 120
        /// </summary>
        [StringLength(120)]
        string COMMENTS { get; set;}
        DateTime? REVDATE { get; set;}
    }
}
#pragma warning restore 1591
