// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.Ihpms
{
	[IAlias("ROADWAY")]
    public partial interface IROADWAY :ZZHMHN.IBase.I_Entity.IEntity
    {
        [Required]
		[PrimaryKey]
        int RDWAYID { get; set;}		
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string TYPE { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string FACILITY { get; set;}
		/// <summary>
        /// length: 6
        /// </summary>
        [StringLength(6)]
        string ROADNUM { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string STATUS { get; set;}
        DateTime? BEGINDATE { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string MAINTRESP { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string PRIMARYDIR { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        string SECONDDIR { get; set;}
		/// <summary>
        /// length: 60
        /// </summary>
        [StringLength(60)]
        string COMMENTS { get; set;}
        DateTime? REVDATE { get; set;}
    }
}
#pragma warning restore 1591
