// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ZZHMHN.IBase.I_Entity;

namespace ZZHMHN.IBase.I_Entity.Ihpms
{
	[IAlias("t_basis_roads")]
    public partial interface It_basis_road :ZZHMHN.IBase.I_Entity.IEntity
    {
        [AutoIncrement]
		[PrimaryKey]
        int id { get; set;}		
		/// <summary>
        /// length: 100
        /// </summary>
        [StringLength(100)]
        string name { get; set;}
		/// <summary>
        /// length: 1000
        /// </summary>
        [StringLength(1000)]
        string comment { get; set;}
    }
}
#pragma warning restore 1591
