// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Prefer
{
	[Alias("Budget_Constraints")]
    public partial class Budget_Constraint :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.IPrefer.IBudget_Constraint
    {
		public Budget_Constraint()
		{
		}

        public decimal? BudService { get; set;}
        public decimal? BudSafety { get; set;}
        public decimal? BudRehabi { get; set;}
    }
}
#pragma warning restore 1591
