// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Prefer
{
	[Alias("Pave_Score_Weigh_Factors")]
    public partial class Pave_Score_Weigh_Factor :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.IPrefer.IPave_Score_Weigh_Factor
    {
		public Pave_Score_Weigh_Factor()
		{
		}

        [Required]
		[PrimaryKey]
        public short CODE { get; set;}		
        public double? Cx_Coefficient { get; set;}
        public double? PCI_Coefficient { get; set;}
        public double? Ride_Coefficient { get; set;}
        public double? FN_Coefficient { get; set;}
    }
}
#pragma warning restore 1591
