// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Prefer
{
	[Alias("Structural_DesignParameters")]
    public partial class Structural_DesignParameter :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.IPrefer.IStructural_DesignParameter
    {
		public Structural_DesignParameter()
		{
		}

        [Required]
		[PrimaryKey]
        public short CODE { get; set;}		
        public double? ACC_Design_Life { get; set;}
        public double? PCC_Design_Life { get; set;}
    }
}
#pragma warning restore 1591
