// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Prefer
{
	[Alias("Traffic_Parameters2")]
    public partial class Traffic_Parameters2 :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.IPrefer.ITraffic_Parameters2
    {
		public Traffic_Parameters2()
		{
		}

        [Required]
		[PrimaryKey]
        public short CODE { get; set;}		
        public double? Growth_Rate { get; set;}
        public double? Low_ESAL { get; set;}
        public double? High_ESAL { get; set;}
        public double? Low_AADT { get; set;}
        public double? High_AADT { get; set;}
    }
}
#pragma warning restore 1591
