// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Archive
{
	[Alias("RDDIST")]
    public partial class RDDIST :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.IArchive.IRDDIST
    {
		public RDDIST()
		{
		}

        [Required]
		[PrimaryKey]
        public int ArchID { get; set;}		
        public double? SEGID { get; set;}
        public double? DISTID { get; set;}
        public DateTime? DISTDATE { get; set;}
        public double? QUANLOW { get; set;}
        public double? QUANMED { get; set;}
        public double? QUANHI { get; set;}
        public double? QUANNA { get; set;}
        public double? TOTSIZE { get; set;}
    }
}
#pragma warning restore 1591
