// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Ihpms
{
	[Alias("DISTTYPE")]
    public partial class DISTTYPE :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.Ihpms.IDISTTYPE
    {
		public DISTTYPE()
		{
		}

        [Alias("DISTRESS ID")]
        [Required]
		[PrimaryKey]
        public double DISTRESS_ID { get; set;}		
        [Alias("DISTRESS NAME")]
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        public string DISTRESS_NAME { get; set;}
        [Alias("DISTRESS UNIT")]
        public double? DISTRESS_UNIT { get; set;}
        public double? Severity { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        public string STRUCTURETYPE { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        public string RDPCINAME { get; set;}
    }
}
#pragma warning restore 1591
