// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Ihpms
{
	[Alias("DTPARAM")]
    public partial class DTPARAM :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.Ihpms.IDTPARAM
    {
		public DTPARAM()
		{
		}

        [AutoIncrement]
		[PrimaryKey]
        public decimal PARAM_ID { get; set;}		
        [Required]
		[PrimaryKey]
        public int SET_ID { get; set;}		
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        public string PARAM_NAME { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        public string STNDNAME { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string TYPE_DCSN { get; set;}
        public short? DEFAULT_BR { get; set;}
        public int? PARAM_ORD { get; set;}
        public short? P1 { get; set;}
        public short? P2 { get; set;}
        public short? P3 { get; set;}
    }
}
#pragma warning restore 1591
