// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Ihpms
{
	[Alias("PMSFILES")]
    public partial class PMSFILE :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.Ihpms.IPMSFILE
    {
		public PMSFILE()
		{
		}

		/// <summary>
        /// length: 12
        /// </summary>
        [StringLength(12)]
        [Required]
		[PrimaryKey]
        public string FILE_NAME { get; set;}		
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        public string DB_Name { get; set;}
		/// <summary>
        /// length: 254
        /// </summary>
        [StringLength(254)]
        public string DESCRPTION { get; set;}
        public bool? DBLIST { get; set;}
        public bool? MDB { get; set;}
        public bool? PART_MDB { get; set;}
		/// <summary>
        /// length: 254
        /// </summary>
        [StringLength(254)]
        public string COMMENTS { get; set;}
        public DateTime? REV_DATE { get; set;}
    }
}
#pragma warning restore 1591
