// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Ihpms
{
	[Alias("RDTRF")]
    public partial class RDTRF :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.Ihpms.IRDTRF
    {
		public RDTRF()
		{
		}

        [Required]
		[PrimaryKey]
        public int SEGID { get; set;}		
        public int? CURADT { get; set;}
        public int? CURADTYEAR { get; set;}
        public float? DIRSPLTPCT { get; set;}
        public float? GROWTHRATE { get; set;}
        public float? TRKPCTAADT { get; set;}
        public float? TRKWTPAT { get; set;}
		/// <summary>
        /// length: 50
        /// </summary>
        [StringLength(50)]
        public string COMMENTS { get; set;}
    }
}
#pragma warning restore 1591
