// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Ihpms
{
	[Alias("ROADWAY")]
    public partial class ROADWAY :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.Ihpms.IROADWAY
    {
		public ROADWAY()
		{
		}

        [Required]
		[PrimaryKey]
        public int RDWAYID { get; set;}		
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string TYPE { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string FACILITY { get; set;}
		/// <summary>
        /// length: 6
        /// </summary>
        [StringLength(6)]
        public string ROADNUM { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string STATUS { get; set;}
        public DateTime? BEGINDATE { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string MAINTRESP { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string PRIMARYDIR { get; set;}
		/// <summary>
        /// length: 1
        /// </summary>
        [StringLength(1)]
        public string SECONDDIR { get; set;}
		/// <summary>
        /// length: 60
        /// </summary>
        [StringLength(60)]
        public string COMMENTS { get; set;}
        public DateTime? REVDATE { get; set;}
    }
}
#pragma warning restore 1591
