// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Ihpms
{
	[Alias("SAMPDATA")]
    public partial class SAMPDATUM :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.Ihpms.ISAMPDATUM
    {
		public SAMPDATUM()
		{
		}

		/// <summary>
        /// length: 30
        /// </summary>
        [StringLength(30)]
        [Required]
		[PrimaryKey]
        public string SAMPID { get; set;}		
        [Required]
		[PrimaryKey]
        public short SEGID { get; set;}		
        [Required]
		[PrimaryKey]
        public short DISTID { get; set;}		
        public short? QUANTLOW { get; set;}
        public short? QUANTMED { get; set;}
        public short? QUANTHI { get; set;}
        public short? QUANTNA { get; set;}
    }
}
#pragma warning restore 1591
