// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Ihpms
{
	[Alias("t_basis_roads")]
    public partial class t_basis_road :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.Ihpms.It_basis_road
    {
		public t_basis_road()
		{
		}

        [AutoIncrement]
		[PrimaryKey]
        public int id { get; set;}		
		/// <summary>
        /// length: 100
        /// </summary>
        [StringLength(100)]
        public string name { get; set;}
		/// <summary>
        /// length: 1000
        /// </summary>
        [StringLength(1000)]
        public string comment { get; set;}
    }
}
#pragma warning restore 1591
