// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Prefer
{
	[Alias("Default_Option")]
    public partial class Default_Option :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.IPrefer.IDefault_Option
    {
		public Default_Option()
		{
		}

        public double? InflaRate { get; set;}
        public double? InterRate { get; set;}
        public double? ThinThickness { get; set;}
        public double? ThickThickness { get; set;}
        public double? NewACThickness { get; set;}
        public double? NewPCCThickness { get; set;}
        public double? SufThreshhold { get; set;}
        [Required]
        public bool MissingFlag { get; set;}
        [Required]
        public bool PvmtMaint { get; set;}
        [Required]
        public bool WearMaint { get; set;}
    }
}
#pragma warning restore 1591
