// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Prefer
{
	[Alias("Friction_Model_Coefficients")]
    public partial class Friction_Model_Coefficient :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.IPrefer.IFriction_Model_Coefficient
    {
		public Friction_Model_Coefficient()
		{
		}

        [Required]
		[PrimaryKey]
        public short CODE { get; set;}		
        public int? Method { get; set;}
        public bool? SelectedOption { get; set;}
        public double? Fri_Coefficient_a0 { get; set;}
        public double? Fri_Coefficient_a1 { get; set;}
        public double? Fri_Coefficient_a2 { get; set;}
        public double? Fri_Coefficient_a3 { get; set;}
    }
}
#pragma warning restore 1591
