// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Prefer
{
	[Alias("Maint_Effect_Coefficients")]
    public partial class Maint_Effect_Coefficient :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.IPrefer.IMaint_Effect_Coefficient
    {
		public Maint_Effect_Coefficient()
		{
		}

        public double? CoefficientValue { get; set;}
		/// <summary>
        /// length: 100
        /// </summary>
        [StringLength(100)]
        public string Description { get; set;}
    }
}
#pragma warning restore 1591
