// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Prefer
{
	[Alias("PCI_Model_Coefficient")]
    public partial class PCI_Model_Coefficient :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.IPrefer.IPCI_Model_Coefficient
    {
		public PCI_Model_Coefficient()
		{
		}

        [Required]
		[PrimaryKey]
        public int Method { get; set;}		
        [Required]
		[PrimaryKey]
        public short PavementCODE { get; set;}		
        [Required]
		[PrimaryKey]
        public short FunctionalCODE { get; set;}		
        public int? SelectedOption { get; set;}
        public double? Low_ESAL_a0 { get; set;}
        public double? Low_ESAL_a1 { get; set;}
        public double? Low_ESAL_a2 { get; set;}
        public double? Low_ESAL_a3 { get; set;}
        public double? Medium_ESAL_a0 { get; set;}
        public double? Medium_ESAL_a1 { get; set;}
        public double? Medium_ESAL_a2 { get; set;}
        public double? Medium_ESAL_a3 { get; set;}
        public double? High_ESAL_a0 { get; set;}
        public double? High_ESAL_a1 { get; set;}
        public double? High_ESAL_a2 { get; set;}
        public double? High_ESAL_a3 { get; set;}
    }
}
#pragma warning restore 1591
