// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Prefer
{
	[Alias("Performance_Threshold")]
    public partial class Performance_Threshold :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.IPrefer.IPerformance_Threshold
    {
		public Performance_Threshold()
		{
		}

        [Required]
		[PrimaryKey]
        public short SurfaceTypeCODE { get; set;}		
        [Required]
		[PrimaryKey]
        public short FunClassCODE { get; set;}		
        public double? VolCapRatio { get; set;}
        public double? NumAccidents { get; set;}
        public double? Roughness { get; set;}
        public double? PCI_Preventive { get; set;}
        public double? PCI_Corrective { get; set;}
        public double? PCI_Rehabilitation { get; set;}
        public double? PCI_Reconstruction { get; set;}
        public double? WCI_Minor { get; set;}
        public double? WCI_Remove_Replace { get; set;}
        public double? WCI_Bridge { get; set;}
        public double? FN { get; set;}
    }
}
#pragma warning restore 1591
