// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Prefer
{
	[Alias("Priority_Factors")]
    public partial class Priority_Factor :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.IPrefer.IPriority_Factor
    {
		public Priority_Factor()
		{
		}

        [Required]
		[PrimaryKey]
        public short CODE { get; set;}		
        public short? LAADT_LScore { get; set;}
        public short? LAADT_MScore { get; set;}
        public short? LAADT_HScore { get; set;}
        public short? MAADT_LScore { get; set;}
        public short? MAADT_MScore { get; set;}
        public short? MAADT_HScore { get; set;}
        public short? HAADT_LScore { get; set;}
        public short? HAADT_MScore { get; set;}
        public short? HAADT_HScore { get; set;}
    }
}
#pragma warning restore 1591
