// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ZZHMHN.Web.Entity.Prefer
{
	[Alias("Traffic_Parameters")]
    public partial class Traffic_Parameter :ZZHMHN.Web.Core.EntityBase, ZZHMHN.IBase.I_Entity.IPrefer.ITraffic_Parameter
    {
		public Traffic_Parameter()
		{
		}

        public double? Lane_Factor { get; set;}
        public short? Truck_Pattern { get; set;}
        public double? Equi_18Kip_Load { get; set;}
    }
}
#pragma warning restore 1591
